### ISSUE TITLE
Still seeing occasional missed pages because Redfishtool does not wait long enough

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfishtool#15]
In my test, seems to give up too quickly for some pages that require access to internal IPMI resources.
There was discussion. Is there a fix pending for this?
Adding -vvvvv makes page fetches succeed.

**Comment by mraineri** [comment]
Can we get any timing metrics to see how long it takes for these pages to be returned?

**Comment by jbobzin-insyde** [comment]
Using internal tests, Insyde has identified a couple pages with longer response times and is doing coding improvements.   But currently do not see the timeouts with Redfish-Service-Validator because that program seems to have more liberal timeout and retry policies. 

My recollection is Paul stated the maintainers of RedfishTool were considering some improvements in timeouts? But perhaps I misunderstood or misremembered?

This problem is now more apparent because RedfishTool is  the core of the usecase testers.  Somehow that changes the experience compared with CLI mode.

**Comment by mraineri** [comment]
As a test, could you try adding "-T 30" when running redfishtool?

**Comment by mraineri** [comment]
Would like to see what HTTP generally uses as a timeout; supposedly it is 30 seconds. Should do some research to confirm.

**Comment by billdodd** [comment]
In Redfishtool, the default read timeout is 10 seconds and the default connect timeout is 3 seconds.

I wasn't able to find any universal HTTP timeout guidelines. Different clients use different values.

It would be helpful to know what kind of timeout it is getting (read timeout, connect timeout, something else) in order to see if there may be a retry logic error in the code. The tool prints an error message on ReadTimeout. But only prints a verbosity 5 message on ConnectTimeout and some of the other conditions. This is unfortunate since Jeff notes that with "-vvvvv" the timeouts don't happen.

It may be worthwhile to make a code update to change the verbosity 5 messages in rftSendRecvRequest() to errors or verbosity 1 messages as appropriate in order to get better diagnostics.
