### ISSUE TITLE
Redfishtool need option to get object by odata.type

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfishtool#22]
The tools has code to parse odata.type from an object (parseOdataType), but no command line option to lookup a resource by its type. This should be something like:

-o, <type>.  --Odata=<type>   -- find the resource with the specified @odata.type

This could be used in combinations with -1, -F, and -all
-o  & -F   == find the first instance of resource with that type
-0 & -1 == find the only instance of resource with that type, and error if there is more than 1
-o & -a == find all instances of the resource with that type

**Comment by mraineri** [comment]
Some things to consider before proceeding with this sort of request:
- Since `@odata.type` has schema version info, does the user need to provide the exact type? This might be difficult for a user to use
- Resources of the same type could be spread out across a service, which can make it very slow to complete

Is there a particular use case you're trying to address?

**Comment by mraineri** [comment]
This seems to be in python-redfish-library (it also used caching to save on time). Might not be achievable since there are lots of applications where they do not want to cache data.

Use case: Suppose you have multiple implementations with different URI schemas; would like to easily reset all Computer Systems without having to loop through the list responses (which can be difficult in a command line script).

Could consider modifying the "-a" argument to be used for PUTs, PATCHes, etc. for Chassis and Systems
