### ISSUE TITLE
Why Redfish?

### ISSUE THREAD

**Issue by Sumitkm897** [DMTF/Redfishtool#79]
Why is there a need for this Redfish when we already have similar technologies like REST,..etc?

**Comment by jautor** [comment]
From our response on the DMTF's Redfish School channel on YouTube:  
https://www.youtube.com/watch?v=LvG9XQ3AqNM

Redfish is a RESTful interface that uses HTTP/HTTPS as the network transport, along with JSON responses.  The standard describes the implementation details for that interface to provide interoperability among vendors (HTTP headers, HTTP response code usage, Action formats, etc.).  But more importantly, Redfish describes the resources and data returned by the service side, so that the property names and data formats are consistent between vendor implementations.  For example a unit’s serial number is always returned as a string value for a property named “SerialNumber” -  not “serial-number”, “serial#”, “productSKUNumber”, etc.  The resources are rigidly defined by “schema files” that allow both humans and coding/testing tools to comprehend those definitions.
