### ISSUE TITLE
Systems Processors and Systems Processors list

### ISSUE THREAD

**Issue by andy1990zx** [DMTF/Redfishtool#97]
![image](https://user-images.githubusercontent.com/37032134/135016465-ce9c8a9e-fafb-43c5-bf0e-45f83e2f463a.png)
Hi,

The Systems Processors list command is almost the same as Systems Processors, what's the purpose... shall we remove it to avoid mis-understanding?

Thanks,
Sea

**Comment by mraineri** [comment]
"Processors List" is like "Processors" in that it shows the URIs, but also shows the Id and Socket properties for the processors found (it looks like in your system the second processor is not reporting a "Socket").

At least at the time the tool was written, there was no hardening in Redfish to tie the "Id" property to the last segment of the URI.

I'm not sure if removing it at this time would be beneficial since there may be users relying on that capability "list" exposes.

**Comment by mraineri** [comment]
Closing; no harm in having both commands.
